# Generated by Django 4.2.1 on 2025-03-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='men',
            index=models.Index(fields=['-time_create'], name='men_men_time_cr_642e6a_idx'),
        ),
    ]
