# Generated by Django 4.2.1 on 2025-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_alter_men_options_men_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
