# Generated by Django 4.2.1 on 2025-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0008_wife_men_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='w_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
